export interface UsedCar {
  id: number;
  name: string;
  model: string;
  price: number;
  mileage: number;
  year: number;
  fuelType: 'Petrol' | 'Diesel' | 'Hybrid' | 'Electric';
  transmission: 'Manual' | 'Automatic';
  drivetrain: '4x2' | '4x4';
  bodyType: 'SUV' | 'Double Cab' | 'Hatchback' | 'Crossover';
  location: string;
  colour: string;
  image: string;
  createdAt: string;
  monthlyPayment?: number;
}

export const usedCars: UsedCar[] = [
  {
    id: 1,
    name: 'Haval Jolion 1.5T City 6MT',
    model: 'Jolion',
    price: 309999,
    mileage: 3500,
    year: 2025,
    fuelType: 'Petrol',
    transmission: 'Manual',
    drivetrain: '4x2',
    bodyType: 'SUV',
    location: 'Thorp Plumstead',
    colour: 'White',
    image: '/cars/haval-pro.png',
    createdAt: '2025-01-10',
    monthlyPayment: 5601,
  },
  {
    id: 2,
    name: 'Chery Tiggo 8 Pro Max 2.0T Executive',
    model: 'Tiggo 8',
    price: 529800,
    mileage: 9953,
    year: 2024,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    drivetrain: '4x2',
    bodyType: 'SUV',
    location: 'Thorp Bayside',
    colour: 'Grey',
    image: '/cars/haval-h6.png',
    createdAt: '2025-01-09',
    monthlyPayment: 9572,
  },
  {
    id: 3,
    name: 'Suzuki Jimny 1.5 GLX Auto',
    model: 'Jimny',
    price: 339900,
    mileage: 1,
    year: 2021,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    drivetrain: '4x4',
    bodyType: 'SUV',
    location: 'Thorp Table Bay Mall',
    colour: 'Green',
    image: '/cars/haval-tank-300.png',
    createdAt: '2025-01-08',
    monthlyPayment: 6141,
  },
  {
    id: 4,
    name: 'Suzuki Vitara Brezza 1.5 GLX',
    model: 'Vitara Brezza',
    price: 259800,
    mileage: 55000,
    year: 2022,
    fuelType: 'Petrol',
    transmission: 'Manual',
    drivetrain: '4x2',
    bodyType: 'SUV',
    location: 'Thorp Bayside',
    colour: 'Silver',
    image: '/cars/haval-pro.png',
    createdAt: '2025-01-07',
    monthlyPayment: 4694,
  },
  {
    id: 5,
    name: 'Kia Sportage 2.0CRDi SX AWD',
    model: 'Sportage',
    price: 289800,
    mileage: 127000,
    year: 2017,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    drivetrain: '4x4',
    bodyType: 'SUV',
    location: 'Thorp Bayside',
    colour: 'Black',
    image: '/cars/haval-h6.png',
    createdAt: '2025-01-06',
    monthlyPayment: 5236,
  },
  {
    id: 6,
    name: 'GAC EMKOO 1.5T Executive Plus',
    model: 'EMKOO',
    price: 489800,
    mileage: 5000,
    year: 2025,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    drivetrain: '4x2',
    bodyType: 'SUV',
    location: 'Thorp Bayside',
    colour: 'White',
    image: '/cars/haval-h6-gt.png',
    createdAt: '2025-01-05',
    monthlyPayment: 8849,
  },
  {
    id: 7,
    name: 'Volkswagen Tiguan Allspace 1.4TSI Trendline',
    model: 'Tiguan Allspace',
    price: 349800,
    mileage: 70000,
    year: 2021,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    drivetrain: '4x2',
    bodyType: 'SUV',
    location: 'Thorp Bayside',
    colour: 'White',
    image: '/cars/haval-h7.png',
    createdAt: '2025-01-04',
    monthlyPayment: 6320,
  },
  {
    id: 8,
    name: 'OMODA C5 1.5T Elegance S',
    model: 'C5',
    price: 389800,
    mileage: 5000,
    year: 2025,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    drivetrain: '4x2',
    bodyType: 'SUV',
    location: 'Thorp Bayside',
    colour: 'Blue',
    image: '/cars/haval-h6.png',
    createdAt: '2025-01-03',
    monthlyPayment: 7042,
  },
  {
    id: 9,
    name: 'Chery Tiggo 4 Pro 1.5 LiT CVT',
    model: 'Tiggo 4 Pro',
    price: 269800,
    mileage: 11000,
    year: 2025,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    drivetrain: '4x2',
    bodyType: 'Crossover',
    location: 'Thorp Bayside',
    colour: 'Red',
    image: '/cars/haval-pro.png',
    createdAt: '2025-01-02',
    monthlyPayment: 4874,
  },
  {
    id: 10,
    name: 'Suzuki Jimny 1.5 GL 5Dr',
    model: 'Jimny',
    price: 389900,
    mileage: 1500,
    year: 2023,
    fuelType: 'Petrol',
    transmission: 'Manual',
    drivetrain: '4x4',
    bodyType: 'SUV',
    location: 'Thorp N1 City',
    colour: 'Khaki',
    image: '/cars/haval-tank-300.png',
    createdAt: '2025-01-01',
    monthlyPayment: 7044,
  },
];

export function getUsedCarById(id: number): UsedCar | undefined {
  return usedCars.find((c) => c.id === id);
}
